name: vidhyatri
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.3.4
  logger: ^2.0.2+1
  sandbox_logger: ^2.1.0
  google_nav_bar: ^5.0.6
  rxdart: ^0.27.7

  # local to global
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  firebase_ui_localizations: ^1.10.2
  equatable: ^2.0.5

  #firebase
  firebase_auth: ^4.17.0
  firebase_core: ^2.8.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  firebase_analytics: ^10.8.7
  firebase_crashlytics: ^3.4.16

  # Theme
  flex_color_scheme: ^7.3.1
  flex_seed_scheme: ^1.4.0
  fluttertoast: ^8.2.4
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  firebase_ui_firestore: ^1.6.2
  firebase_ui_shared: ^1.4.1
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  google_ml_kit: ^0.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  # a tool for running code generators
  build_runner: ^2.4.8
  # the code generator
  riverpod_generator: ^2.3.11
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.9
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.6.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
